name: push to Docker Hub
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVersion: [1.17, 1.18]
    env:
      IMAGE_NAME: devanarchy/golang-aws-cli:go${{ matrix.goVersion }}
    steps:
    - uses: actions/checkout@v3
    - run: docker build --build-arg GO_VERSION=${{ matrix.goVersion }} -t ${{ env.IMAGE_NAME }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker push ${{ env.IMAGE_NAME }}